version: '3.9'
services:

  apache:
   build: ./apache
   environment:
    - APACHE_RUN_USER=#1000
   volumes:
    - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
   ports:
    - 8080:80
    - 443:443
   working_dir: ${APP_PATH_CONTAINER}

  db:
   image: mysql:8.0.27
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
    MYSQL_DATABASE: ${MYSQL_DB}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_USER}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_INITDB_SKIP_TZINFO: "yes"
   ports:
    - 3306:3306
   security_opt:
    - seccomp:unconfined
   volumes:
    - ./db/my.cnf:/etc/mysql/my.cnf
    - ${DB_PATH_HOST}:/var/lib/mysql
    - ./mysql-dump:/docker-entrypoint-initdb.d/:rw

  adminer:
   image: adminer
   environment:
    ADMINER_DEFAULT_SERVER: mysql
   restart: always
   ports:
    - 6080:8080

  composer:
   image: composer:2.1.12
   volumes:
    - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
   working_dir: ${APP_PATH_CONTAINER}
   command: composer install
